# Generated by Django 4.2.7 on 2025-11-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="table_number",
            field=models.IntegerField(
                blank=True, help_text="Table number for grouping seats", null=True
            ),
        ),
    ]
