# Generated by Django 4.2.7 on 2025-11-14 07:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("book", "Book"),
                            ("ride", "Ride"),
                            ("lost_found", "Lost & Found"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("reserved", "Reserved"),
                            ("sold", "Sold"),
                            ("completed", "Completed"),
                            ("found", "Found"),
                            ("returned", "Returned"),
                            ("closed", "Closed"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("pickup_location", models.CharField(blank=True, max_length=200, null=True)),
                ("dropoff_location", models.CharField(blank=True, max_length=200, null=True)),
                ("contact_phone", models.CharField(blank=True, max_length=15, null=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "images",
                    models.JSONField(blank=True, default=list, help_text="List of image URLs"),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, help_text="List of tags for search"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("views_count", models.IntegerField(default=0)),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Marketplace Item",
                "verbose_name_plural": "Marketplace Items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketplaceFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "marketplace_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="marketplace.marketplaceitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Marketplace Favorite",
                "verbose_name_plural": "Marketplace Favorites",
            },
        ),
        migrations.CreateModel(
            name="LostFoundItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("electronics", "Electronics"),
                            ("clothing", "Clothing"),
                            ("books", "Books"),
                            ("accessories", "Accessories"),
                            ("documents", "Documents"),
                            ("keys", "Keys"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("size", models.CharField(blank=True, max_length=50, null=True)),
                ("found_location", models.CharField(blank=True, max_length=200, null=True)),
                ("found_date", models.DateField(blank=True, null=True)),
                (
                    "reward_offered",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("verification_required", models.BooleanField(default=False)),
                ("verification_details", models.TextField(blank=True, null=True)),
                (
                    "marketplace_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lost_found_item",
                        to="marketplace.marketplaceitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lost & Found Item",
                "verbose_name_plural": "Lost & Found Items",
            },
        ),
        migrations.CreateModel(
            name="BookListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("isbn", models.CharField(blank=True, max_length=20, null=True)),
                ("author", models.CharField(max_length=200)),
                ("publisher", models.CharField(blank=True, max_length=200, null=True)),
                ("edition", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("like_new", "Like New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("negotiable", models.BooleanField(default=True)),
                ("course_code", models.CharField(blank=True, max_length=20, null=True)),
                ("semester", models.IntegerField(blank=True, null=True)),
                (
                    "marketplace_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_listing",
                        to="marketplace.marketplaceitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Listing",
                "verbose_name_plural": "Book Listings",
            },
        ),
        migrations.CreateModel(
            name="RideListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ride_type",
                    models.CharField(
                        choices=[
                            ("one_way", "One Way"),
                            ("round_trip", "Round Trip"),
                            ("regular", "Regular Commute"),
                        ],
                        default="one_way",
                        max_length=20,
                    ),
                ),
                ("departure_date", models.DateTimeField()),
                ("return_date", models.DateTimeField(blank=True, null=True)),
                ("departure_location", models.CharField(max_length=200)),
                ("destination", models.CharField(max_length=200)),
                (
                    "available_seats",
                    models.IntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "total_seats",
                    models.IntegerField(
                        default=4, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "price_per_seat",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("vehicle_type", models.CharField(blank=True, max_length=50, null=True)),
                ("vehicle_number", models.CharField(blank=True, max_length=20, null=True)),
                ("luggage_space", models.BooleanField(default=False)),
                ("smoking_allowed", models.BooleanField(default=False)),
                ("pets_allowed", models.BooleanField(default=False)),
                (
                    "marketplace_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ride_listing",
                        to="marketplace.marketplaceitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ride Listing",
                "verbose_name_plural": "Ride Listings",
                "indexes": [
                    models.Index(
                        fields=["departure_date", "departure_location"],
                        name="marketplace_departu_53a4e7_idx",
                    ),
                    models.Index(fields=["destination"], name="marketplace_destina_fcb064_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketplaceTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("inquiry", "Inquiry"),
                            ("reservation", "Reservation"),
                            ("purchase", "Purchase"),
                            ("claim", "Claim"),
                            ("message", "Message"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "seats_requested",
                    models.IntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "agreed_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("meeting_location", models.CharField(blank=True, max_length=200, null=True)),
                ("meeting_date", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("review", models.TextField(blank=True, null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "marketplace_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="marketplace.marketplaceitem",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Marketplace Transaction",
                "verbose_name_plural": "Marketplace Transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["marketplace_item", "status"], name="marketplace_marketp_fe4128_idx"
                    ),
                    models.Index(fields=["buyer", "status"], name="marketplace_buyer_i_68831e_idx"),
                    models.Index(
                        fields=["seller", "status"], name="marketplace_seller__35ce42_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="marketplaceitem",
            index=models.Index(
                fields=["item_type", "status", "is_active"], name="marketplace_item_ty_b8dae4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketplaceitem",
            index=models.Index(
                fields=["posted_by", "status"], name="marketplace_posted__783022_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketplaceitem",
            index=models.Index(fields=["-created_at"], name="marketplace_created_4ad093_idx"),
        ),
        migrations.AddIndex(
            model_name="marketplacefavorite",
            index=models.Index(
                fields=["user", "-created_at"], name="marketplace_user_id_cc0ed7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="marketplacefavorite",
            unique_together={("user", "marketplace_item")},
        ),
        migrations.AddIndex(
            model_name="lostfounditem",
            index=models.Index(fields=["category"], name="marketplace_categor_6a7bb9_idx"),
        ),
        migrations.AddIndex(
            model_name="lostfounditem",
            index=models.Index(fields=["found_location"], name="marketplace_found_l_a9e4a5_idx"),
        ),
        migrations.AddIndex(
            model_name="booklisting",
            index=models.Index(fields=["isbn"], name="marketplace_isbn_069966_idx"),
        ),
        migrations.AddIndex(
            model_name="booklisting",
            index=models.Index(fields=["course_code"], name="marketplace_course__98f747_idx"),
        ),
        migrations.AddIndex(
            model_name="booklisting",
            index=models.Index(fields=["price"], name="marketplace_price_df2522_idx"),
        ),
    ]
