# Generated by Django 4.2.7 on 2025-11-13 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="digest_frequency",
            field=models.CharField(
                choices=[("daily", "Daily"), ("weekly", "Weekly"), ("never", "Never")],
                default="never",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="NotificationSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("summary_text", models.TextField()),
                ("summary_type", models.CharField(default="short", max_length=20)),
                ("model_used", models.CharField(blank=True, max_length=100)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("word_count", models.PositiveIntegerField(default=0)),
                ("key_points", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPriorityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_global", models.BooleanField(default=False)),
                ("notification_type", models.CharField(blank=True, max_length=20, null=True)),
                ("keyword", models.CharField(blank=True, max_length=100, null=True)),
                ("sender", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("auto_escalate", models.BooleanField(default=False)),
                ("escalation_minutes", models.PositiveIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="priority_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_active", "priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("essential", "Essential"),
                            ("important", "Important"),
                            ("optional", "Optional"),
                        ],
                        default="important",
                        max_length=20,
                    ),
                ),
                ("notification_types", models.JSONField(blank=True, default=list)),
                ("push_enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("escalation_enabled", models.BooleanField(default=False)),
                ("escalation_delay_minutes", models.PositiveIntegerField(default=60)),
                (
                    "escalate_to_tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("essential", "Essential"),
                            ("important", "Important"),
                            ("optional", "Optional"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_tiers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user", "tier"],
                "unique_together": {("user", "tier")},
            },
        ),
        migrations.CreateModel(
            name="NotificationDigest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly"), ("never", "Never")],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True)),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("notification_count", models.PositiveIntegerField(default=0)),
                ("unread_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notifications",
                    models.ManyToManyField(related_name="digests", to="notifications.notification"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_digests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="notificatio_user_id_601352_idx"
                    ),
                    models.Index(
                        fields=["user", "is_sent", "-created_at"],
                        name="notificatio_user_id_a1f078_idx",
                    ),
                ],
            },
        ),
    ]
