# Generated by Django 4.2.7 on 2025-11-13 09:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("notice", "Notice"),
                            ("study_group", "Study Group"),
                            ("resource", "Resource"),
                            ("meeting", "Meeting"),
                            ("event", "Event"),
                        ],
                        max_length=20,
                    ),
                ),
                ("item1_id", models.IntegerField()),
                ("item2_id", models.IntegerField()),
                (
                    "similarity_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Similarity score (0.0 to 1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "similarity_type",
                    models.CharField(
                        choices=[
                            ("cosine", "Cosine Similarity"),
                            ("jaccard", "Jaccard Similarity"),
                            ("pearson", "Pearson Correlation"),
                            ("euclidean", "Euclidean Distance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("last_calculated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Item Similarity",
                "verbose_name_plural": "Item Similarities",
                "indexes": [
                    models.Index(
                        fields=["content_type", "item1_id", "similarity_type", "similarity_score"],
                        name="recommendat_content_999e86_idx",
                    ),
                    models.Index(
                        fields=["content_type", "item2_id", "similarity_type", "similarity_score"],
                        name="recommendat_content_331e02_idx",
                    ),
                    models.Index(fields=["last_calculated"], name="recommendat_last_ca_9a5272_idx"),
                ],
                "unique_together": {("content_type", "item1_id", "item2_id", "similarity_type")},
            },
        ),
        migrations.CreateModel(
            name="UserSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "similarity_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Similarity score (0.0 to 1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "similarity_type",
                    models.CharField(
                        choices=[
                            ("cosine", "Cosine Similarity"),
                            ("jaccard", "Jaccard Similarity"),
                            ("pearson", "Pearson Correlation"),
                            ("euclidean", "Euclidean Distance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "user1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarities_as_user1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarities_as_user2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Similarity",
                "verbose_name_plural": "User Similarities",
                "indexes": [
                    models.Index(
                        fields=["user1", "similarity_type", "similarity_score"],
                        name="recommendat_user1_i_5fa171_idx",
                    ),
                    models.Index(
                        fields=["user2", "similarity_type", "similarity_score"],
                        name="recommendat_user2_i_7bddd3_idx",
                    ),
                    models.Index(fields=["last_calculated"], name="recommendat_last_ca_05622d_idx"),
                ],
                "unique_together": {("user1", "user2", "similarity_type")},
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("notice", "Notice"),
                            ("study_group", "Study Group"),
                            ("resource", "Resource"),
                            ("meeting", "Meeting"),
                            ("event", "Event"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User preferences (categories, tags, etc.)",
                    ),
                ),
                (
                    "interests",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="User interests (topics, subjects, etc.)",
                    ),
                ),
                (
                    "behavior_patterns",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User behavior patterns (viewing times, interaction types, etc.)",
                    ),
                ),
                (
                    "weight_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Weights for different recommendation factors",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
                "indexes": [
                    models.Index(
                        fields=["user", "content_type"], name="recommendat_user_id_2b1a01_idx"
                    )
                ],
                "unique_together": {("user", "content_type")},
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("notice", "Notice"),
                            ("study_group", "Study Group"),
                            ("resource", "Resource"),
                            ("meeting", "Meeting"),
                            ("event", "Event"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content_id", models.IntegerField()),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("content_based", "Content Based"),
                            ("collaborative", "Collaborative Filtering"),
                            ("ml", "Machine Learning"),
                            ("popular", "Popular"),
                            ("trending", "Trending"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        default=0.0,
                        help_text="Recommendation score (0.0 to 1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Explanation for why this item was recommended",
                        null=True,
                    ),
                ),
                ("is_dismissed", models.BooleanField(default=False)),
                ("is_viewed", models.BooleanField(default=False)),
                ("is_interacted", models.BooleanField(default=False)),
                (
                    "feedback",
                    models.JSONField(
                        blank=True, default=dict, help_text="User feedback on the recommendation"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When this recommendation expires", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommendation",
                "verbose_name_plural": "Recommendations",
                "ordering": ["-score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_dismissed", "is_viewed"],
                        name="recommendat_user_id_d35b96_idx",
                    ),
                    models.Index(
                        fields=["content_type", "content_id"], name="recommendat_content_eaca65_idx"
                    ),
                    models.Index(
                        fields=["recommendation_type", "score"],
                        name="recommendat_recomme_80137d_idx",
                    ),
                    models.Index(fields=["expires_at"], name="recommendat_expires_6bf04d_idx"),
                ],
                "unique_together": {("user", "content_type", "content_id", "recommendation_type")},
            },
        ),
        migrations.CreateModel(
            name="ContentInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("notice", "Notice"),
                            ("study_group", "Study Group"),
                            ("resource", "Resource"),
                            ("meeting", "Meeting"),
                            ("event", "Event"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content_id", models.IntegerField()),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("like", "Like"),
                            ("share", "Share"),
                            ("join", "Join"),
                            ("bookmark", "Bookmark"),
                            ("comment", "Comment"),
                            ("rate", "Rate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Rating (1-5) if applicable",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, help_text="Time spent in seconds (for views)", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the interaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Interaction",
                "verbose_name_plural": "Content Interactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "content_type", "interaction_type"],
                        name="recommendat_user_id_ff2476_idx",
                    ),
                    models.Index(
                        fields=["content_type", "content_id"], name="recommendat_content_fa6f30_idx"
                    ),
                    models.Index(fields=["created_at"], name="recommendat_created_969217_idx"),
                ],
            },
        ),
    ]
