# Generated by Django 4.2.7 on 2025-11-14 13:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "broadcast_type",
                    models.CharField(
                        choices=[
                            ("announcement", "Announcement"),
                            ("event", "Event"),
                            ("alert", "Alert"),
                            ("news", "News"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="announcement",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("important", "Important"),
                            ("urgent", "Urgent"),
                            ("critical", "Critical"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "rich_content",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Rich content (images, videos, links, formatting)",
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(blank=True, default=list, help_text="List of attachment URLs"),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all", "All Users"),
                            ("students", "Students Only"),
                            ("faculty", "Faculty Only"),
                            ("staff", "Staff Only"),
                            ("specific", "Specific Users/Groups"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                (
                    "target_departments",
                    models.JSONField(
                        blank=True, default=list, help_text="List of department names"
                    ),
                ),
                (
                    "target_courses",
                    models.JSONField(blank=True, default=list, help_text="List of course codes"),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("views_count", models.IntegerField(default=0)),
                ("engagement_count", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"user_type__in": ["faculty", "admin"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_broadcasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific users for targeted broadcasts",
                        related_name="targeted_broadcasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Broadcast",
                "verbose_name_plural": "Broadcasts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("case_id", models.CharField(max_length=20, unique=True)),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("complaint", "Complaint"),
                            ("support", "Support Request"),
                            ("incident", "Incident Report"),
                            ("request", "General Request"),
                            ("feedback", "Feedback Case"),
                        ],
                        default="complaint",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("pending", "Pending"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("escalated", "Escalated"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "priority_score",
                    models.IntegerField(default=0, help_text="Calculated priority score"),
                ),
                (
                    "sla_target_hours",
                    models.IntegerField(default=48, help_text="Target resolution time in hours"),
                ),
                ("sla_start_time", models.DateTimeField(auto_now_add=True)),
                ("sla_breach_time", models.DateTimeField(blank=True, null=True)),
                (
                    "sla_status",
                    models.CharField(
                        choices=[
                            ("on_time", "On Time"),
                            ("at_risk", "At Risk"),
                            ("breached", "Breached"),
                        ],
                        default="on_time",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="List of tags for categorization"
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
                ("resolution_time_hours", models.FloatField(blank=True, null=True)),
                ("views_count", models.IntegerField(default=0)),
                ("updates_count", models.IntegerField(default=0)),
                ("response_time_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type__in": ["faculty", "admin"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Case",
                "verbose_name_plural": "Cases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(default="#3b82f6", max_length=7)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Case Tag",
                "verbose_name_plural": "Case Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PredictiveMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("complaint_volume", "Complaint Volume"),
                            ("response_time", "Response Time"),
                            ("resolution_rate", "Resolution Rate"),
                            ("sla_breach", "SLA Breach"),
                            ("attendance_rate", "Attendance Rate"),
                            ("engagement", "Engagement"),
                            ("resource_utilization", "Resource Utilization"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.FloatField()),
                ("predicted_value", models.FloatField(blank=True, null=True)),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Prediction confidence (0-1)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Predictive Metric",
                "verbose_name_plural": "Predictive Metrics",
                "ordering": ["-period_end"],
                "indexes": [
                    models.Index(
                        fields=["metric_type", "period_end"], name="faculty_adm_metric__323479_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CaseUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField()),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False, help_text="Internal notes not visible to case creator"
                    ),
                ),
                ("status_change", models.CharField(blank=True, max_length=20, null=True)),
                ("priority_change", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="faculty_admin.case",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="case_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Update",
                "verbose_name_plural": "Case Updates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BroadcastEngagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("shared", models.BooleanField(default=False)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagements",
                        to="faculty_admin.broadcast",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_engagements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Broadcast Engagement",
                "verbose_name_plural": "Broadcast Engagements",
            },
        ),
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("class", "Class"),
                            ("event", "Event"),
                            ("meeting", "Meeting"),
                            ("workshop", "Workshop"),
                            ("exam", "Exam"),
                            ("other", "Other"),
                        ],
                        default="class",
                        max_length=20,
                    ),
                ),
                (
                    "course_id",
                    models.IntegerField(blank=True, help_text="Reference to Course ID", null=True),
                ),
                (
                    "calendar_event_id",
                    models.IntegerField(
                        blank=True, help_text="Reference to Calendar Event ID", null=True
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("qr_code", models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ("qr_code_expires_at", models.DateTimeField(blank=True, null=True)),
                ("allow_late_marking", models.BooleanField(default=True)),
                ("late_threshold_minutes", models.IntegerField(default=15)),
                ("require_location", models.BooleanField(default=False)),
                ("location_radius_meters", models.IntegerField(default=100)),
                ("expected_location", models.CharField(blank=True, max_length=200, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"user_type__in": ["faculty", "admin"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_attendance_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Session",
                "verbose_name_plural": "Attendance Sessions",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("late", "Late"),
                            ("absent", "Absent"),
                            ("excused", "Excused"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                ("scanned_at", models.DateTimeField(blank=True, null=True)),
                ("qr_code_used", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "location_latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "location_longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                ("device_info", models.JSONField(blank=True, default=dict)),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_notes", models.TextField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="faculty_admin.attendancesession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type__in": ["faculty", "admin"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
            },
        ),
        migrations.CreateModel(
            name="OperationalAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("sla_risk", "SLA Risk"),
                            ("high_volume", "High Volume"),
                            ("resource_shortage", "Resource Shortage"),
                            ("trend_anomaly", "Trend Anomaly"),
                            ("performance_degradation", "Performance Degradation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="faculty_admin.case",
                    ),
                ),
                (
                    "related_metric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="faculty_admin.predictivemetric",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operational Alert",
                "verbose_name_plural": "Operational Alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["alert_type", "severity", "is_acknowledged"],
                        name="faculty_adm_alert_t_cd2035_idx",
                    ),
                    models.Index(
                        fields=["is_acknowledged", "is_resolved"],
                        name="faculty_adm_is_ackn_bf6134_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["case_id"], name="faculty_adm_case_id_2e3772_idx"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["status", "priority"], name="faculty_adm_status_a5cd74_idx"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["assigned_to", "status"], name="faculty_adm_assigne_2ca102_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["sla_status", "sla_breach_time"], name="faculty_adm_sla_sta_79ce05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="broadcastengagement",
            index=models.Index(fields=["broadcast", "user"], name="faculty_adm_broadca_c8dcbf_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="broadcastengagement",
            unique_together={("broadcast", "user")},
        ),
        migrations.AddIndex(
            model_name="broadcast",
            index=models.Index(
                fields=["broadcast_type", "is_published"], name="faculty_adm_broadca_4f8bef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="broadcast",
            index=models.Index(
                fields=["scheduled_at", "is_published"], name="faculty_adm_schedul_b2938b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="broadcast",
            index=models.Index(fields=["created_by"], name="faculty_adm_created_cf9fb9_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["qr_code", "is_active"], name="faculty_adm_qr_code_5ceb3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["created_by", "start_time"], name="faculty_adm_created_fc7ead_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["course_id", "start_time"], name="faculty_adm_course__c1c448_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["session", "status"], name="faculty_adm_session_14ec6d_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["user", "scanned_at"], name="faculty_adm_user_id_35d248_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("session", "user")},
        ),
    ]
