# Generated by Django 5.0.7 on 2025-11-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faculty_admin", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendancesession",
            name="created_by",
        ),
        migrations.AlterField(
            model_name="predictivemetric",
            name="metric_type",
            field=models.CharField(
                choices=[
                    ("complaint_volume", "Complaint Volume"),
                    ("response_time", "Response Time"),
                    ("resolution_rate", "Resolution Rate"),
                    ("sla_breach", "SLA Breach"),
                    ("engagement", "Engagement"),
                    ("resource_utilization", "Resource Utilization"),
                ],
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="AttendanceRecord",
        ),
        migrations.DeleteModel(
            name="AttendanceSession",
        ),
    ]
