// Mocks generated by Mockito 5.4.6 from annotations
// in ksit_nexus_app/test/widget_tests/test_auth_widgets.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:ksit_nexus_app/models/user_model.dart' as _i2;
import 'package:ksit_nexus_app/services/auth_service.dart' as _i3;
import 'package:ksit_nexus_app/services/biometric_service.dart' as _i7;
import 'package:ksit_nexus_app/services/two_factor_service.dart' as _i6;
import 'package:local_auth/local_auth.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#isLoggedIn), returnValue: false)
          as bool);

  @override
  bool get isStudent =>
      (super.noSuchMethod(Invocation.getter(#isStudent), returnValue: false)
          as bool);

  @override
  bool get isFaculty =>
      (super.noSuchMethod(Invocation.getter(#isFaculty), returnValue: false)
          as bool);

  @override
  bool get isAdmin =>
      (super.noSuchMethod(Invocation.getter(#isAdmin), returnValue: false)
          as bool);

  @override
  String get displayName =>
      (super.noSuchMethod(
            Invocation.getter(#displayName),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#displayName),
            ),
          )
          as String);

  @override
  String get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
          )
          as String);

  @override
  String get userType =>
      (super.noSuchMethod(
            Invocation.getter(#userType),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#userType),
            ),
          )
          as String);

  @override
  _i5.Future<bool> checkAuthStatus() =>
      (super.noSuchMethod(
            Invocation.method(#checkAuthStatus, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> isBiometricAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isBiometricAvailable, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> isBiometricEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isBiometricEnabled, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> enableBiometric() =>
      (super.noSuchMethod(
            Invocation.method(#enableBiometric, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> disableBiometric() =>
      (super.noSuchMethod(
            Invocation.method(#disableBiometric, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i2.User?> loginWithBiometric() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithBiometric, []),
            returnValue: _i5.Future<_i2.User?>.value(),
          )
          as _i5.Future<_i2.User?>);

  @override
  _i5.Future<Map<String, dynamic>> getBiometricStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getBiometricStatus, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<_i2.User> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i5.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#login, [username, password]),
              ),
            ),
          )
          as _i5.Future<_i2.User>);

  @override
  _i5.Future<Map<String, dynamic>> register({
    required String? username,
    required String? email,
    required String? password,
    required String? firstName,
    required String? lastName,
    required String? userType,
    String? phoneNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #username: username,
              #email: email,
              #password: password,
              #firstName: firstName,
              #lastName: lastName,
              #userType: userType,
              #phoneNumber: phoneNumber,
            }),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<_i2.User> verifyRegistrationOTP(int? userId, String? otp) =>
      (super.noSuchMethod(
            Invocation.method(#verifyRegistrationOTP, [userId, otp]),
            returnValue: _i5.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#verifyRegistrationOTP, [userId, otp]),
              ),
            ),
          )
          as _i5.Future<_i2.User>);

  @override
  _i5.Future<void> requestOTP(String? email, String? type) =>
      (super.noSuchMethod(
            Invocation.method(#requestOTP, [email, type]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.User> verifyOTP(String? email, String? otp) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOTP, [email, otp]),
            returnValue: _i5.Future<_i2.User>.value(
              _FakeUser_0(this, Invocation.method(#verifyOTP, [email, otp])),
            ),
          )
          as _i5.Future<_i2.User>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> changePassword({
    required String? oldPassword,
    required String? newPassword,
    required String? confirmPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #oldPassword: oldPassword,
              #newPassword: newPassword,
              #confirmPassword: confirmPassword,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.User> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i5.Future<_i2.User>.value(
              _FakeUser_0(this, Invocation.method(#getCurrentUser, [])),
            ),
          )
          as _i5.Future<_i2.User>);

  @override
  _i5.Future<_i2.User> updateProfile({
    required String? firstName,
    required String? lastName,
    String? phoneNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #firstName: firstName,
              #lastName: lastName,
              #phoneNumber: phoneNumber,
            }),
            returnValue: _i5.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#updateProfile, [], {
                  #firstName: firstName,
                  #lastName: lastName,
                  #phoneNumber: phoneNumber,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.User>);

  @override
  _i5.Future<_i2.User> updateProfilePicture(String? imageUrl) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfilePicture, [imageUrl]),
            returnValue: _i5.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#updateProfilePicture, [imageUrl]),
              ),
            ),
          )
          as _i5.Future<_i2.User>);

  @override
  _i5.Future<Map<String, dynamic>> requestPasswordResetOTP(
    String? phoneNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#requestPasswordResetOTP, [phoneNumber]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> verifyPasswordResetOTP(
    String? phoneNumber,
    String? otp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPasswordResetOTP, [phoneNumber, otp]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<_i2.User> resetPassword(
    String? resetToken,
    String? newPassword,
    String? confirmPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [
              resetToken,
              newPassword,
              confirmPassword,
            ]),
            returnValue: _i5.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#resetPassword, [
                  resetToken,
                  newPassword,
                  confirmPassword,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.User>);
}

/// A class which mocks [TwoFactorService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTwoFactorService extends _i1.Mock implements _i6.TwoFactorService {
  MockTwoFactorService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<Map<String, dynamic>> setup2FA() =>
      (super.noSuchMethod(
            Invocation.method(#setup2FA, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> verify2FA(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#verify2FA, [code]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> disable2FA(String? password, String? code) =>
      (super.noSuchMethod(
            Invocation.method(#disable2FA, [password, code]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> get2FAStatus() =>
      (super.noSuchMethod(
            Invocation.method(#get2FAStatus, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> generateBackupCodes(String? password) =>
      (super.noSuchMethod(
            Invocation.method(#generateBackupCodes, [password]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getActiveSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveSessions, []),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<Map<String, dynamic>> createCurrentDeviceSession() =>
      (super.noSuchMethod(
            Invocation.method(#createCurrentDeviceSession, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> deactivateSession(int? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#deactivateSession, [sessionId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> logoutAllDevices(int? currentSessionId) =>
      (super.noSuchMethod(
            Invocation.method(#logoutAllDevices, [currentSessionId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> loginWith2FA({
    required String? username,
    required String? password,
    String? code,
    String? backupCode,
    required String? deviceId,
    required String? deviceName,
    required String? deviceType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loginWith2FA, [], {
              #username: username,
              #password: password,
              #code: code,
              #backupCode: backupCode,
              #deviceId: deviceId,
              #deviceName: deviceName,
              #deviceType: deviceType,
            }),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<bool> is2FAEnabledLocally() =>
      (super.noSuchMethod(
            Invocation.method(#is2FAEnabledLocally, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> set2FAEnabledLocally(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#set2FAEnabledLocally, [enabled]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> getDeviceId() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceId, []),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(this, Invocation.method(#getDeviceId, [])),
            ),
          )
          as _i5.Future<String>);
}

/// A class which mocks [BiometricService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBiometricService extends _i1.Mock implements _i7.BiometricService {
  MockBiometricService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> isBiometricAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isBiometricAvailable, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i8.BiometricType>> getAvailableBiometrics() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableBiometrics, []),
            returnValue: _i5.Future<List<_i8.BiometricType>>.value(
              <_i8.BiometricType>[],
            ),
          )
          as _i5.Future<List<_i8.BiometricType>>);

  @override
  _i5.Future<bool> isBiometricEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isBiometricEnabled, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> enableBiometric() =>
      (super.noSuchMethod(
            Invocation.method(#enableBiometric, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> disableBiometric() =>
      (super.noSuchMethod(
            Invocation.method(#disableBiometric, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> authenticate({
    required String? reason,
    bool? useErrorDialogs = true,
    bool? stickyAuth = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [], {
              #reason: reason,
              #useErrorDialogs: useErrorDialogs,
              #stickyAuth: stickyAuth,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> authenticateForLogin() =>
      (super.noSuchMethod(
            Invocation.method(#authenticateForLogin, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> authenticateForSensitiveOperation() =>
      (super.noSuchMethod(
            Invocation.method(#authenticateForSensitiveOperation, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  String getBiometricTypeName(_i8.BiometricType? type) =>
      (super.noSuchMethod(
            Invocation.method(#getBiometricTypeName, [type]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#getBiometricTypeName, [type]),
            ),
          )
          as String);

  @override
  _i5.Future<List<String>> getAvailableBiometricNames() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableBiometricNames, []),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<bool> hasStrongBiometric() =>
      (super.noSuchMethod(
            Invocation.method(#hasStrongBiometric, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<Map<String, dynamic>> getBiometricStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getBiometricStatus, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);
}
