# Generated by Django 5.0.7 on 2025-09-19 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="facultyfeedback",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "student"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_feedback",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
