# Generated by Django 4.2.7 on 2025-09-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_twofactorauth_devicesession"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpverification",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("registration", "Registration"),
                    ("password_reset", "Password Reset"),
                    ("login", "Login"),
                ],
                default="registration",
                max_length=20,
            ),
        ),
    ]
