# Generated by Django 5.0.7 on 2025-09-22 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_otpverification_purpose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 10-15 digits, optionally starting with +.",
                        regex="^\\+?\\d{10,15}$",
                    )
                ],
            ),
        ),
    ]
