# Generated by Django 5.0.7 on 2025-11-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="usn",
            field=models.CharField(
                blank=True, help_text="University Seat Number", max_length=20, null=True
            ),
        ),
        migrations.CreateModel(
            name="AllowedUSN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "usn",
                    models.CharField(
                        help_text="University Seat Number", max_length=20, unique=True
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        blank=True, help_text="Branch/Department", max_length=100, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Allowed USN",
                "verbose_name_plural": "Allowed USNs",
                "ordering": ["usn"],
                "indexes": [models.Index(fields=["usn"], name="accounts_al_usn_558e81_idx")],
            },
        ),
    ]
