# Generated by Django 4.2.7 on 2025-11-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_student_usn_allowedusn"),
    ]

    operations = [
        migrations.AddField(
            model_name="allowedusn",
            name="name",
            field=models.CharField(blank=True, help_text="Student Name", max_length=200, null=True),
        ),
    ]
