# Generated by Django 4.2.7 on 2025-11-13 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("study_groups", "0006_resource_category"),
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("meeting", "Meeting"),
                            ("deadline", "Deadline"),
                            ("class", "Class"),
                            ("exam", "Exam"),
                            ("reminder", "Reminder"),
                            ("event", "Event"),
                            ("study_session", "Study Session"),
                            ("other", "Other"),
                        ],
                        default="event",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("all_day", models.BooleanField(default=False)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("meeting_link", models.URLField(blank=True, null=True)),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurrence_pattern",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("recurrence_end_date", models.DateTimeField(blank=True, null=True)),
                ("recurrence_count", models.IntegerField(blank=True, null=True)),
                ("color", models.CharField(default="#3b82f6", max_length=7)),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("shared", "Shared"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("external_attendees", models.JSONField(blank=True, default=list)),
                ("is_cancelled", models.BooleanField(default=False)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attendees",
                    models.ManyToManyField(
                        blank=True, related_name="calendar_events", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_calendar_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_events",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "related_study_group_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_events",
                        to="study_groups.upcomingevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar Event",
                "verbose_name_plural": "Calendar Events",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="GoogleCalendarSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_connected", models.BooleanField(default=False)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("calendar_id", models.CharField(blank=True, max_length=200, null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("sync_enabled", models.BooleanField(default=True)),
                (
                    "sync_direction",
                    models.CharField(
                        choices=[
                            ("bidirectional", "Bidirectional"),
                            ("to_google", "To Google Calendar"),
                            ("from_google", "From Google Calendar"),
                        ],
                        default="bidirectional",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_calendar_sync",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Calendar Sync",
                "verbose_name_plural": "Google Calendar Syncs",
                "indexes": [
                    models.Index(
                        fields=["user", "is_connected"], name="calendars_g_user_id_1ec03f_idx"
                    ),
                    models.Index(fields=["sync_enabled"], name="calendars_g_sync_en_52fa76_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("notification", "Notification"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                        ],
                        default="notification",
                        max_length=20,
                    ),
                ),
                (
                    "minutes_before",
                    models.IntegerField(
                        choices=[
                            (0, "At event time"),
                            (5, "5 minutes before"),
                            (15, "15 minutes before"),
                            (30, "30 minutes before"),
                            (60, "1 hour before"),
                            (120, "2 hours before"),
                            (1440, "1 day before"),
                            (2880, "2 days before"),
                        ],
                        default=15,
                    ),
                ),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="calendars.calendarevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Reminder",
                "verbose_name_plural": "Event Reminders",
                "ordering": ["minutes_before"],
                "indexes": [
                    models.Index(fields=["event", "user"], name="calendars_e_event_i_cd684a_idx"),
                    models.Index(fields=["is_sent"], name="calendars_e_is_sent_299b92_idx"),
                ],
                "unique_together": {("event", "user", "reminder_type", "minutes_before")},
            },
        ),
        migrations.CreateModel(
            name="CalendarEventSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("google_calendar_id", models.CharField(blank=True, max_length=200, null=True)),
                ("ical_uid", models.CharField(blank=True, max_length=200, null=True)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("synced", "Synced"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_records",
                        to="calendars.calendarevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar Event Sync",
                "verbose_name_plural": "Calendar Event Syncs",
                "indexes": [
                    models.Index(fields=["event"], name="calendars_c_event_i_6fa3b3_idx"),
                    models.Index(fields=["sync_status"], name="calendars_c_sync_st_05b3ad_idx"),
                ],
                "unique_together": {("event", "ical_uid"), ("event", "google_calendar_id")},
            },
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(
                fields=["start_time", "end_time"], name="calendars_c_start_t_f5ea39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(fields=["event_type"], name="calendars_c_event_t_d59366_idx"),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(fields=["created_by"], name="calendars_c_created_210f30_idx"),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(fields=["is_cancelled"], name="calendars_c_is_canc_f1f538_idx"),
        ),
    ]
