# Generated by Django 4.2.7 on 2025-11-20 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("first_login", "First Login"),
                            ("profile_complete", "Profile Complete"),
                            ("study_group_created", "Study Group Created"),
                            ("study_group_joined", "Study Group Joined"),
                            ("notice_viewed", "Notice Viewed"),
                            ("complaint_submitted", "Complaint Submitted"),
                            ("feedback_submitted", "Feedback Submitted"),
                            ("event_created", "Event Created"),
                            ("event_attended", "Event Attended"),
                            ("streak_daily", "Daily Streak"),
                            ("streak_weekly", "Weekly Streak"),
                            ("points_milestone", "Points Milestone"),
                            ("social_contributor", "Social Contributor"),
                            ("academic_excellence", "Academic Excellence"),
                            ("community_helper", "Community Helper"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                        ],
                        default="bronze",
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=100, null=True)),
                ("points_reward", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "requirements",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Requirements to unlock this achievement (e.g., {"count": 10, "type": "study_groups"})',
                    ),
                ),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
                "ordering": ["difficulty", "points_reward"],
            },
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "leaderboard_type",
                    models.CharField(
                        choices=[
                            ("points", "Points"),
                            ("achievements", "Achievements"),
                            ("study_groups", "Study Groups"),
                            ("contributions", "Contributions"),
                            ("streak", "Streak"),
                            ("overall", "Overall"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("all_time", "All Time"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("period_start", models.DateTimeField(blank=True, null=True)),
                ("period_end", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Leaderboard Entry",
                "verbose_name_plural": "Leaderboard Entries",
                "ordering": ["-score"],
            },
        ),
        migrations.CreateModel(
            name="PointTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.IntegerField(help_text="Positive for earned, negative for spent"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("achievement", "Achievement"),
                            ("daily_login", "Daily Login"),
                            ("study_group_activity", "Study Group Activity"),
                            ("complaint_submission", "Complaint Submission"),
                            ("feedback_submission", "Feedback Submission"),
                            ("event_creation", "Event Creation"),
                            ("event_attendance", "Event Attendance"),
                            ("social_interaction", "Social Interaction"),
                            ("content_contribution", "Content Contribution"),
                            ("milestone", "Milestone"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "balance_after",
                    models.IntegerField(help_text="Points balance after this transaction"),
                ),
                ("related_object_type", models.CharField(blank=True, max_length=50, null=True)),
                ("related_object_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Point Transaction",
                "verbose_name_plural": "Point Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("badge", "Badge"),
                            ("discount", "Discount"),
                            ("privilege", "Privilege"),
                            ("recognition", "Recognition"),
                            ("physical", "Physical Item"),
                        ],
                        max_length=20,
                    ),
                ),
                ("points_cost", models.IntegerField()),
                ("icon", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "stock_quantity",
                    models.IntegerField(blank=True, help_text="Null for unlimited", null=True),
                ),
                (
                    "redemption_limit",
                    models.IntegerField(
                        blank=True,
                        help_text="Max redemptions per user (null for unlimited)",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional reward data (e.g., discount code, badge details)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reward",
                "verbose_name_plural": "Rewards",
                "ordering": ["points_cost"],
            },
        ),
        migrations.CreateModel(
            name="UserStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("last_login_date", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Streak",
                "verbose_name_plural": "User Streaks",
            },
        ),
        migrations.CreateModel(
            name="UserPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_points", models.IntegerField(default=0)),
                (
                    "current_points",
                    models.IntegerField(default=0, help_text="Points available for redemption"),
                ),
                (
                    "lifetime_points",
                    models.IntegerField(default=0, help_text="Total points ever earned"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Points",
                "verbose_name_plural": "User Points",
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Current progress towards achievement"
                    ),
                ),
                ("is_unlocked", models.BooleanField(default=False)),
                ("unlocked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_achievements",
                        to="gamification.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Achievement",
                "verbose_name_plural": "User Achievements",
            },
        ),
        migrations.CreateModel(
            name="RewardRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("points_spent", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("fulfilled", "Fulfilled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="gamification.reward",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reward Redemption",
                "verbose_name_plural": "Reward Redemptions",
                "ordering": ["-redeemed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="reward",
            index=models.Index(
                fields=["is_active", "points_cost"], name="gamificatio_is_acti_dc9363_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reward",
            index=models.Index(fields=["reward_type"], name="gamificatio_reward__0c0c69_idx"),
        ),
        migrations.AddField(
            model_name="pointtransaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="point_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaderboard_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="achievement",
            index=models.Index(
                fields=["achievement_type", "is_active"], name="gamificatio_achieve_dc7813_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="achievement",
            index=models.Index(fields=["difficulty"], name="gamificatio_difficu_c3e700_idx"),
        ),
        migrations.AddIndex(
            model_name="userpoints",
            index=models.Index(fields=["total_points"], name="gamificatio_total_p_b385ab_idx"),
        ),
        migrations.AddIndex(
            model_name="userpoints",
            index=models.Index(fields=["-total_points"], name="gamificatio_total_p_68f463_idx"),
        ),
        migrations.AddIndex(
            model_name="userachievement",
            index=models.Index(
                fields=["user", "is_unlocked"], name="gamificatio_user_id_69f856_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userachievement",
            index=models.Index(
                fields=["achievement", "is_unlocked"], name="gamificatio_achieve_c8cf0a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userachievement",
            unique_together={("user", "achievement")},
        ),
        migrations.AddIndex(
            model_name="rewardredemption",
            index=models.Index(
                fields=["user", "-redeemed_at"], name="gamificatio_user_id_f80c22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rewardredemption",
            index=models.Index(fields=["status"], name="gamificatio_status_086702_idx"),
        ),
        migrations.AddIndex(
            model_name="rewardredemption",
            index=models.Index(fields=["reward", "status"], name="gamificatio_reward__744bb1_idx"),
        ),
        migrations.AddIndex(
            model_name="pointtransaction",
            index=models.Index(
                fields=["user", "-created_at"], name="gamificatio_user_id_b86e52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pointtransaction",
            index=models.Index(fields=["source"], name="gamificatio_source_9df610_idx"),
        ),
        migrations.AddIndex(
            model_name="leaderboard",
            index=models.Index(
                fields=["leaderboard_type", "period", "-score"],
                name="gamificatio_leaderb_6979e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leaderboard",
            index=models.Index(
                fields=["user", "leaderboard_type", "period"], name="gamificatio_user_id_2be293_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leaderboard",
            unique_together={("user", "leaderboard_type", "period", "period_start")},
        ),
    ]
