# Generated by Django 4.2.7 on 2025-11-13 14:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CounselingService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Counseling"),
                            ("career", "Career Counseling"),
                            ("mental_health", "Mental Health"),
                            ("personal", "Personal Counseling"),
                            ("crisis", "Crisis Support"),
                            ("peer", "Peer Support"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("counselor_name", models.CharField(blank=True, max_length=200, null=True)),
                ("counselor_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("counselor_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "available_hours",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Available hours (e.g., {"monday": "9:00-17:00"})',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, help_text="Allow anonymous appointments"),
                ),
            ],
            options={
                "verbose_name": "Counseling Service",
                "verbose_name_plural": "Counseling Services",
                "ordering": ["service_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("security", "Security"),
                            ("medical", "Medical"),
                            ("fire", "Fire Department"),
                            ("police", "Police"),
                            ("campus_admin", "Campus Administration"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("alternate_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Display priority (higher = shown first)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency Contact",
                "verbose_name_plural": "Emergency Contacts",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="SafetyResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("guide", "Safety Guide"),
                            ("video", "Video Resource"),
                            ("article", "Article"),
                            ("contact", "Contact Information"),
                            ("tool", "Tool/App"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("content", models.TextField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="safety_resources/")),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("views_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Safety Resource",
                "verbose_name_plural": "Safety Resources",
                "ordering": ["-is_featured", "title"],
            },
        ),
        migrations.CreateModel(
            name="UserPersonalEmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("family", "Family"),
                            ("friend", "Friend"),
                            ("guardian", "Guardian"),
                            ("colleague", "Colleague"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("alternate_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "relationship",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Mother, Father, Friend",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, help_text="Primary contact to notify first"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_emergency_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal Emergency Contact",
                "verbose_name_plural": "Personal Emergency Contacts",
                "ordering": ["-is_primary", "name"],
                "unique_together": {("user", "phone_number")},
            },
        ),
        migrations.CreateModel(
            name="EmergencyAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("alert_id", models.CharField(max_length=20, unique=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("medical", "Medical Emergency"),
                            ("security", "Security Threat"),
                            ("fire", "Fire"),
                            ("natural_disaster", "Natural Disaster"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="high",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                ("response_notes", models.TextField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("broadcast_to_all", models.BooleanField(default=True)),
                ("target_departments", models.JSONField(blank=True, default=list)),
                ("target_buildings", models.JSONField(blank=True, default=list)),
                ("views_count", models.IntegerField(default=0)),
                ("acknowledgments_count", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_emergency_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notify_contacts",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Personal emergency contacts to notify about this alert",
                        related_name="alerts",
                        to="safety_wellbeing.userpersonalemergencycontact",
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type__in": ["faculty", "admin", "staff"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responded_emergency_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency Alert",
                "verbose_name_plural": "Emergency Alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyAcknowledgment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("acknowledged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location_latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "location_longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                ("is_safe", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgments",
                        to="safety_wellbeing.emergencyalert",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_acknowledgments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency Acknowledgment",
                "verbose_name_plural": "Emergency Acknowledgments",
            },
        ),
        migrations.CreateModel(
            name="CounselingAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("appointment_id", models.CharField(max_length=20, unique=True)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("scheduled_at", models.DateTimeField()),
                (
                    "duration_minutes",
                    models.IntegerField(
                        default=60, validators=[django.core.validators.MinValueValidator(15)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("contact_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("preferred_name", models.CharField(blank=True, max_length=100, null=True)),
                ("reason", models.TextField(help_text="Reason for appointment")),
                ("notes", models.TextField(blank=True, help_text="Additional notes", null=True)),
                (
                    "counselor_notes",
                    models.TextField(
                        blank=True, help_text="Counselor notes (not visible to user)", null=True
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_date", models.DateTimeField(blank=True, null=True)),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        help_text="User rating (1-5)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("feedback", models.TextField(blank=True, null=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="safety_wellbeing.counselingservice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Counseling Appointment",
                "verbose_name_plural": "Counseling Appointments",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="AnonymousCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("check_in_id", models.CharField(max_length=20, unique=True)),
                (
                    "check_in_type",
                    models.CharField(
                        choices=[
                            ("wellness", "Wellness Check"),
                            ("stress", "Stress Management"),
                            ("anxiety", "Anxiety Support"),
                            ("depression", "Depression Support"),
                            ("crisis", "Crisis Support"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mood_level",
                    models.IntegerField(
                        choices=[
                            (1, "Very Low"),
                            (2, "Low"),
                            (3, "Neutral"),
                            (4, "Good"),
                            (5, "Very Good"),
                        ],
                        default=3,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("contact_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("allow_follow_up", models.BooleanField(default=False)),
                ("response_notes", models.TextField(blank=True, null=True)),
                ("response_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type__in": ["faculty", "admin", "staff"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responded_check_ins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Anonymous Check-In",
                "verbose_name_plural": "Anonymous Check-Ins",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="emergencyalert",
            index=models.Index(
                fields=["alert_id", "status"], name="safety_well_alert_i_24668a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyalert",
            index=models.Index(fields=["status", "severity"], name="safety_well_status_0ab833_idx"),
        ),
        migrations.AddIndex(
            model_name="emergencyalert",
            index=models.Index(fields=["created_at"], name="safety_well_created_980b34_idx"),
        ),
        migrations.AddIndex(
            model_name="emergencyacknowledgment",
            index=models.Index(fields=["alert", "user"], name="safety_well_alert_i_64d644_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="emergencyacknowledgment",
            unique_together={("alert", "user")},
        ),
        migrations.AddIndex(
            model_name="counselingappointment",
            index=models.Index(
                fields=["appointment_id", "status"], name="safety_well_appoint_fca2eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="counselingappointment",
            index=models.Index(
                fields=["service", "scheduled_at"], name="safety_well_service_3ba7c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="counselingappointment",
            index=models.Index(
                fields=["user", "scheduled_at"], name="safety_well_user_id_aa14ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="counselingappointment",
            index=models.Index(
                fields=["status", "scheduled_at"], name="safety_well_status_f3bd35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anonymouscheckin",
            index=models.Index(fields=["check_in_id"], name="safety_well_check_i_b6998d_idx"),
        ),
        migrations.AddIndex(
            model_name="anonymouscheckin",
            index=models.Index(
                fields=["check_in_type", "mood_level"], name="safety_well_check_i_40f58c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anonymouscheckin",
            index=models.Index(fields=["created_at"], name="safety_well_created_eeeb30_idx"),
        ),
    ]
