# Generated by Django 4.2.7 on 2025-12-03 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("api_call", "API Call"),
                            ("database_query", "Database Query"),
                            ("notification", "Send Notification"),
                            ("calendar", "Calendar Action"),
                            ("reservation", "Reservation Action"),
                            ("study_group", "Study Group Action"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("action_config", models.JSONField(blank=True, default=dict)),
                ("required_params", models.JSONField(blank=True, default=list)),
                ("optional_params", models.JSONField(blank=True, default=list)),
                ("execution_function", models.CharField(blank=True, max_length=200, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("failure_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Chatbot Action",
                "verbose_name_plural": "Chatbot Actions",
            },
        ),
        migrations.CreateModel(
            name="ChatbotCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Chatbot Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ChatbotSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatbot_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("context_variables", models.JSONField(blank=True, default=dict)),
                ("current_intent", models.CharField(blank=True, max_length=100, null=True)),
                ("conversation_state", models.CharField(default="idle", max_length=50)),
                ("detected_entities", models.JSONField(blank=True, default=list)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("sentiment_label", models.CharField(blank=True, max_length=20, null=True)),
                ("conversation_history", models.JSONField(blank=True, default=list)),
                ("max_history_length", models.IntegerField(default=10)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_context",
                        to="chatbot.chatbotsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation Context",
                "verbose_name_plural": "Conversation Contexts",
            },
        ),
        migrations.CreateModel(
            name="ChatbotUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("preferred_language", models.CharField(default="en", max_length=10)),
                (
                    "response_style",
                    models.CharField(
                        choices=[
                            ("formal", "Formal"),
                            ("casual", "Casual"),
                            ("friendly", "Friendly"),
                            ("professional", "Professional"),
                        ],
                        default="friendly",
                        max_length=20,
                    ),
                ),
                ("total_interactions", models.IntegerField(default=0)),
                ("total_sessions", models.IntegerField(default=0)),
                ("average_rating", models.FloatField(default=0.0)),
                ("preferences", models.JSONField(blank=True, default=dict)),
                ("common_topics", models.JSONField(blank=True, default=list)),
                ("preferred_categories", models.JSONField(blank=True, default=list)),
                ("last_interaction_at", models.DateTimeField(blank=True, null=True)),
                ("is_personalized", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatbot_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chatbot User Profile",
                "verbose_name_plural": "Chatbot User Profiles",
            },
        ),
        migrations.CreateModel(
            name="ChatbotQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="chatbot.chatbotcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-usage_count", "question"],
            },
        ),
        migrations.CreateModel(
            name="ChatbotMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("user", "User Message"),
                            ("bot", "Bot Response"),
                            ("system", "System Message"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("is_helpful", models.BooleanField(blank=True, null=True)),
                ("feedback_comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="chatbot.chatbotquestion",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chatbot.chatbotsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatbotFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Not Helpful"),
                            (2, "2 - Slightly Helpful"),
                            (3, "3 - Moderately Helpful"),
                            (4, "4 - Very Helpful"),
                            (5, "5 - Extremely Helpful"),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="chatbot.chatbotmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chatbot_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatbotAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("total_sessions", models.IntegerField(default=0)),
                ("total_messages", models.IntegerField(default=0)),
                ("unique_users", models.IntegerField(default=0)),
                ("most_asked_questions", models.JSONField(blank=True, default=list)),
                ("unanswered_questions", models.JSONField(blank=True, default=list)),
                ("average_response_time", models.FloatField(default=0.0)),
                ("average_rating", models.FloatField(default=0.0)),
                ("resolution_rate", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("date",)},
            },
        ),
        migrations.CreateModel(
            name="ChatbotActionExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("execution_time", models.FloatField(blank=True, null=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="chatbot.chatbotaction",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_executions",
                        to="chatbot.chatbotsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chatbot_action_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chatbot Action Execution",
                "verbose_name_plural": "Chatbot Action Executions",
            },
        ),
        migrations.AddIndex(
            model_name="chatbotaction",
            index=models.Index(
                fields=["action_type", "is_active"], name="chatbot_cha_action__4c9b71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatbotaction",
            index=models.Index(fields=["name"], name="chatbot_cha_name_7f8678_idx"),
        ),
        migrations.AddIndex(
            model_name="conversationcontext",
            index=models.Index(
                fields=["session", "is_active"], name="chatbot_con_session_564c45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationcontext",
            index=models.Index(fields=["current_intent"], name="chatbot_con_current_9a09ec_idx"),
        ),
        migrations.AddIndex(
            model_name="conversationcontext",
            index=models.Index(
                fields=["conversation_state"], name="chatbot_con_convers_0bd7da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatbotuserprofile",
            index=models.Index(fields=["user"], name="chatbot_cha_user_id_7e50cb_idx"),
        ),
        migrations.AddIndex(
            model_name="chatbotuserprofile",
            index=models.Index(fields=["is_personalized"], name="chatbot_cha_is_pers_487d8f_idx"),
        ),
        migrations.AddIndex(
            model_name="chatbotactionexecution",
            index=models.Index(fields=["action", "status"], name="chatbot_cha_action__7f676e_idx"),
        ),
        migrations.AddIndex(
            model_name="chatbotactionexecution",
            index=models.Index(fields=["session"], name="chatbot_cha_session_e9cf19_idx"),
        ),
        migrations.AddIndex(
            model_name="chatbotactionexecution",
            index=models.Index(fields=["user"], name="chatbot_cha_user_id_d2987a_idx"),
        ),
        migrations.AddIndex(
            model_name="chatbotactionexecution",
            index=models.Index(fields=["created_at"], name="chatbot_cha_created_9eed95_idx"),
        ),
    ]
