# Generated by Django 4.2.7 on 2025-12-03 23:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("assignment_due", "Assignment Due"),
                            ("exam", "Exam"),
                            ("class", "Class"),
                            ("deadline", "Deadline"),
                            ("grade_release", "Grade Release"),
                            ("course_registration", "Course Registration"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("reminder_date", models.DateTimeField()),
                ("is_recurring", models.BooleanField(default=False)),
                ("recurrence_pattern", models.CharField(blank=True, max_length=20, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("notification_sent", models.BooleanField(default=False)),
                ("notification_sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Academic Reminder",
                "verbose_name_plural": "Academic Reminders",
                "ordering": ["reminder_date"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("homework", "Homework"),
                            ("project", "Project"),
                            ("lab_report", "Lab Report"),
                            ("essay", "Essay"),
                            ("presentation", "Presentation"),
                            ("quiz", "Quiz"),
                            ("midterm", "Midterm"),
                            ("final", "Final Exam"),
                            ("other", "Other"),
                        ],
                        default="homework",
                        max_length=20,
                    ),
                ),
                ("assigned_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("due_date", models.DateTimeField()),
                ("late_submission_allowed", models.BooleanField(default=False)),
                (
                    "late_penalty_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                            ("late", "Late"),
                            ("missed", "Missed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("submission_link", models.URLField(blank=True, null=True)),
                (
                    "submission_file",
                    models.FileField(blank=True, null=True, upload_to="assignments/"),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Weight percentage in final grade",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("feedback", models.TextField(blank=True, null=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_sent", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course_code", models.CharField(max_length=20, unique=True)),
                ("course_name", models.CharField(max_length=200)),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("core", "Core"),
                            ("elective", "Elective"),
                            ("lab", "Laboratory"),
                            ("project", "Project"),
                            ("seminar", "Seminar"),
                            ("workshop", "Workshop"),
                        ],
                        default="core",
                        max_length=20,
                    ),
                ),
                (
                    "credits",
                    models.IntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "semester",
                    models.IntegerField(
                        choices=[
                            (1, "Semester 1"),
                            (2, "Semester 2"),
                            (3, "Semester 3"),
                            (4, "Semester 4"),
                            (5, "Semester 5"),
                            (6, "Semester 6"),
                            (7, "Semester 7"),
                            (8, "Semester 8"),
                        ]
                    ),
                ),
                ("academic_year", models.CharField(help_text="e.g., 2024-2025", max_length=20)),
                ("description", models.TextField(blank=True, null=True)),
                ("syllabus", models.TextField(blank=True, null=True)),
                (
                    "schedule",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Course schedule (days, times, location)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "color",
                    models.CharField(default="#3b82f6", help_text="Hex color for UI", max_length=7),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ["semester", "course_code"],
            },
        ),
        migrations.CreateModel(
            name="CourseEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("dropped", "Dropped"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="enrolled",
                        max_length=20,
                    ),
                ),
                ("enrollment_date", models.DateField(default=django.utils.timezone.now)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("final_grade", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "grade_points",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Enrollment",
                "verbose_name_plural": "Course Enrollments",
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "S (Outstanding)"),
                            ("A", "A (Excellent)"),
                            ("B", "B (Very Good)"),
                            ("C", "C (Good)"),
                            ("D", "D (Satisfactory)"),
                            ("E", "E (Pass)"),
                            ("F", "F (Fail)"),
                            ("I", "I (Incomplete)"),
                            ("W", "W (Withdrawn)"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "grade_points",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "assignment_scores",
                    models.JSONField(
                        blank=True, default=dict, help_text="Breakdown of scores by assignment type"
                    ),
                ),
                ("semester", models.IntegerField(blank=True, null=True)),
                ("academic_year", models.CharField(blank=True, max_length=20, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_final", models.BooleanField(default=False)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="academic_planner.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade",
                "verbose_name_plural": "Grades",
                "ordering": ["-semester", "-academic_year"],
            },
        ),
    ]
