# Generated by Django 4.2.7 on 2025-12-03 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academic_planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="courseenrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="academic_planner.course",
            ),
        ),
        migrations.AddField(
            model_name="courseenrollment",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_enrollments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "faculty"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taught_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="academic_planner.course",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "faculty"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="student",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "student"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="academicreminder",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="academic_planner.assignment",
            ),
        ),
        migrations.AddField(
            model_name="academicreminder",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="academic_planner.course",
            ),
        ),
        migrations.AddField(
            model_name="academicreminder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_reminders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["student", "semester"], name="academic_pl_student_d56af7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["course", "semester"], name="academic_pl_course__82076a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(fields=["grade"], name="academic_pl_grade_927005_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together={("student", "course", "semester", "academic_year")},
        ),
        migrations.AddIndex(
            model_name="courseenrollment",
            index=models.Index(fields=["student", "status"], name="academic_pl_student_e19de7_idx"),
        ),
        migrations.AddIndex(
            model_name="courseenrollment",
            index=models.Index(fields=["course", "status"], name="academic_pl_course__c2c964_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="courseenrollment",
            unique_together={("student", "course")},
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["course_code"], name="academic_pl_course__896ebe_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["semester", "academic_year"], name="academic_pl_semeste_14dc7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["instructor"], name="academic_pl_instruc_42c005_idx"),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["course", "due_date"], name="academic_pl_course__0da57b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(fields=["student", "status"], name="academic_pl_student_d94f99_idx"),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["due_date", "status"], name="academic_pl_due_dat_eb5f67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicreminder",
            index=models.Index(
                fields=["user", "reminder_date"], name="academic_pl_user_id_b5de6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicreminder",
            index=models.Index(
                fields=["course", "reminder_date"], name="academic_pl_course__c1aaa1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicreminder",
            index=models.Index(
                fields=["is_completed", "reminder_date"], name="academic_pl_is_comp_861f3e_idx"
            ),
        ),
    ]
