# Generated by Django 5.0.7 on 2025-09-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study_groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upcomingevent",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
