# Generated by Django 5.0.7 on 2025-09-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study_groups", "0002_alter_upcomingevent_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upcomingevent",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
