# Generated by Django 5.0.7 on 2025-10-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0005_studygroup_is_reported_studygroup_report_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(blank=True, choices=[('lecture_notes', 'Lecture Notes'), ('assignment', 'Assignment'), ('exam_material', 'Exam Material'), ('reference', 'Reference'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
